# Generated by Django 4.0.4 on 2022-07-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
